import React from "react";

function AboutUs() {
  return (
    <div>
      <div className="relative py-2 border-gray-50 border">
        <div
          className="absolute inset-0 bg-cover bg-center z-0"
          style={{
            backgroundImage: "url('https://broaster.com/wp-content/uploads/BroasterFoods-WideTableGroup-Crop-1024x332.jpg')",
            backgroundBlendMode: "multiply",
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            backgroundSize: "cover",
            backgroundPosition: "center",
            position: "absolute",
            top: 0,
            left: 0,
            height: "100%",
            width: "100%",
            zIndex: -1,
            opacity: 0.5,
          }}></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 ">
          <div className="mt-16 text-center">
            <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
              <span className="block text-black">Impressed by the app?</span>
              <span className="block text-indigo-600">Intrigued by the idea?</span>
            </h1>
            <p className="mt-3 max-w-md mx-auto text-base text-white sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">Why not hire the brain behind it? I promise, there's more where that came from!</p>
          </div>
        </div>
      </div>
      <div className="mt-10 max-w-7xl mx-auto px-4 sm:px-6 bg-white shadow-md rounded-lg p-6">
        <div className="mb-6 bg-gray-100 p-4 rounded-md">
          <h2 className="text-2xl font-bold mb-2">Idea</h2>
          <p className="text-gray-700">
            Though this project is to showcase my ability in web development, it started as an idea. Bothered by waiting for food on a hungry stomach (which would feel like hours), I had this idea to
            order ahead of time and reach there when the food is ready. This was the basis of the project.
          </p>
        </div>

        <div className="mb-6 bg-gray-100 p-4 rounded-md">
          <h2 className="text-2xl font-bold mb-2">Development Process</h2>
          <p className="text-gray-700">
            Prior to this I've had experience in development in two internships. However, Spring Boot was relatively new though. I've spent my time trying to strengthen the fundamentals of the Spring
            framework. Once I started feeling comfortable, I made no late in building the product. It was from scratch, designing the schemas, their relations, the backend flow, and the frontend. I've
            tried to follow the industry standards that I'm aware of.
          </p>
        </div>

        <div className="mb-6 bg-gray-100 p-4 rounded-md">
          <h2 className="text-2xl font-bold mb-2">Use of AI</h2>
          <p className="text-gray-700">
            This is the page with the most minimal use of AI throughout the project. Wouldn't it be foolish not utilizing the available resources, it would be if one is not in a state to judge the
            quality of the code generated by AI. It has just made the entire process much quicker.
          </p>
        </div>

        <div className="mb-6 bg-gray-100 p-4 rounded-md">
          <h2 className="text-2xl font-bold mb-2">Tech Used</h2>
          <p className="text-gray-700">SpringBoot3, MySQL, React, Tailwind CSS.</p>
        </div>

        {/* <div className="mb-6 bg-gray-100 p-4 rounded-md">
          <h2 className="text-2xl font-bold mb-2">Challenges faced</h2>
          <p className="text-gray-700">
            Apart from the use of different annotations to manipulate data and wire objects during the initial stints of spring development, I faced a huge challenge while deployment (Atleast felt like it).
            I deployed the backend on AWS (which was a different story altogether but was not as much challenging), and by default it is open to communicate only over HTTP. To configure it to HTTPS, apparently one needs an SSL certificate which is not free - one needs to own a domain. This is where I realized when to go to chatbots and when to go to stackoverflow.
          </p>
        </div> */}
      </div>
    </div>
  );
}

export default AboutUs;
